### ISSUE TITLE
 Will future versions of VectorAdmin support other types of Embeddings?

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/vector-admin#103]
Will future versions of VectorAdmin support other types of Embeddings? such as all-MiniLM-L6-v2

**Comment by timothycarambat** [comment]
Yes, it will! We currently only started with OpenAI since that is where a lot of the current demand was situation. In the future you will be able to select your embedder/model so that you can properly upsert or modify embeddings withing VectorAdmin

**Comment by ctxwing** [comment]
@timothycarambat 
thanks for th e greate job. especially , i do like the part that i could see what's in it vector store..

me too, sooo curious the other types of Embeddings much.. 
any progress or roadmap for this ?
