### ISSUE TITLE
[FEAT]:  Include marketing site in source code

### ISSUE THREAD

**Issue by cameronking4** [Mintplex-Labs/vector-admin#140]
### What would you like to see?

Awesome landing page, would you include in repo?

**Comment by timothycarambat** [comment]
Im not sure what the request is here? We have our landing page in the repo already via the links?

**Comment by cameronking4** [comment]
Thanks for quick response :)

**Comment by cameronking4** [comment]
Looking for source of https://vectoradmin.com/ landing page

**Comment by timothycarambat** [comment]
That is a framer.app site, there is no source code. The template is the [Wenius](https://www.framer.com/templates/wenius/) template but updated and designed by our designer
