### ISSUE TITLE
[BUG]: Fetch Failed while connecting to chromadb

### ISSUE THREAD

**Issue by hasani114** [Mintplex-Labs/vector-admin#146]
### How are you running VectorAdmin?

Docker (local)

### What happened?

I have a docker instance of chromadb running on port 8000 which is accessible. When I insert the URL it just says "fetch failed"

![image](https://github.com/user-attachments/assets/2ca955f9-778a-4c0e-9630-c0d09b9fddd6)

**Comment by timothycarambat** [comment]
If you are in docker you cannot use localhost since that is a special hostname that loopsback to the container. Use `HTTP://host.docker.internal:8000` https://github.com/Mintplex-Labs/vector-admin/blob/39fe4a1117a81feaf09a440b79792120964bb4d6/docker/DOCKER.md#connecting-to-a-vector-database
