### ISSUE TITLE
[BUG]: Unable to build docker container from source (No matching distribution found for install==1.3.5)

### ISSUE THREAD

**Issue by danielbarillo** [Mintplex-Labs/vector-admin#149]
### How are you running VectorAdmin?

Docker (local)

### What happened?

After setting up a local postgresql container I'm running `docker-compose up -d --build vector-admin` which crashes with the following error:

```
5.688 ERROR: Could not find a version that satisfies the requirement install==1.3.5 (from versions: none)
5.688 ERROR: No matching distribution found for install==1.3.5

failed to solve: process "/bin/sh -c cd /app/document-processor &&     python3 -m virtualenv v-env &&     . v-env/bin/activate &&     pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
```

I'm not very familiar with the packages required for the document processor but I searched on PyPi for the package and it seems that it has changed name, so...

Possible solution:
Change `install==1.3.5` to `pip-install==1.3.5` in `/document-processor/requirements.txt`

With that change the build was successful and now everything is running, but this is my first time testing the application so I will have to poke around to see if it's working as intended

### Are there known steps to reproduce?

Build the docker containers from source as described in the readme

**Comment by 3x3cut0r** [comment]
same issue here. i created a [pull requrest](https://github.com/Mintplex-Labs/vector-admin/pull/150) to fix the requirements.txt.
