### ISSUE TITLE
implement more vector database apps

### ISSUE THREAD

**Issue by AorsiniYT** [Mintplex-Labs/vector-admin#20]
Will you put an implementation for the vector apps? like milvus, or also zilliz which would be the same as milvus

**Comment by timothycarambat** [comment]
Scoped to be implemented currently are
- Weaviate
- qDrant

Are you a Milvus user currently and want to use that?

**Comment by AorsiniYT** [comment]
yes, I am a milvus user

**Comment by bhctest123** [comment]
@timothycarambat I really like the weaviate and qDrant picks! those are very helpful for my business focused use cases!

**Comment by warjiang** [comment]
> Scoped to be implemented currently are
> 
> * Weaviate
> * qDrant
> 
> Are you a Milvus user currently and want to use that?

Weaviate + 1,  pleasure to offer any contribute, like api alignment or fronted dev

**Comment by bhctest123** [comment]
Hi @timothycarambat any idea on when support for Qdrant or Weaviate is planned?  If not planned yet, is this the type of project you are open to participation from others?  If so, would you be able to create a ticket describing how you would implement it that I can use for a developer to contribute?

**Comment by timothycarambat** [comment]
> Hi @timothycarambat any idea on when support for Qdrant or Weaviate is planned? If not planned yet, is this the type of project you are open to participation from others? If so, would you be able to create a ticket describing how you would implement it that I can use for a developer to contribute?

It's open-source so contributors are of course welcome! We just added Weaviate support to AnythingLLM and will be bringing VectorAdmin to do the same. In general we just want to make sure that additional vector dbs are feature complete with all others.

So connect, entire db sync, workspace/namespace/class sync, CRUD records and all that. So it all comes down to the `vectordb` providers all looking the same and having the same interface. That being said adding a whole new vector db is a massive task and can be, and likely should, be left to the core team at the current build state. How soon are you needing those vector db's supported? What is the use case as well?

**Comment by bhctest123** [comment]
There are a lot of business use cases i have for weaviate and qdrant, other open source projects I am using rely on one or both of those DBs.  I see vector admin as a way to mitigate the risk that the data is stuck in there.  

I also like that I can abstract away the vector db altogether if I can migrate from one vector db to another.  I see Vector Admin as a potentially integral part of the stack once you have enough vector db coverage.  

I am guessing you are internally balancing feature dev and vector db dev, i know that must be a lot of lift.  I imagine each new vector db you add expands your addressable market of vector db users….

**Comment by timothycarambat** [comment]
@bhctest123 Indeed it does, which is why Weaviate and Qdrant are next up for integrations. We just added them into AnythingLLM (where we pilot new vector databases first) and it was pretty simple. Expect those two integrated soon!

**Comment by 8times4** [comment]
Would love to have a Milvus integration in the future :)

**Comment by timothycarambat** [comment]
Qdrant integration has been completed in PR #52 🚀

**Comment by timothycarambat** [comment]
Weaviate was also added recently with full feature support. Closing this thread for now as we are going to hold off on new database support simply because we dont want to overbuild and want to gauge the appetite of a tool like Vector Admin
