### ISSUE TITLE
Pinecone support for Vectors without namespace

### ISSUE THREAD

**Issue by ilanb** [Mintplex-Labs/vector-admin#21]
I'v some pinecone vector index without namespace and vector admin can't find database:
{
  "message": "No Pinecone namespace found for vectors-without-namespace - nothing to do."
}

**Comment by martin-242** [comment]
Would love this since otherwise Pinecone free tier cannot be used with Vector-Admin.

**Comment by Nikto655** [comment]
Im using free tier Pinecone and it seems to work?

**Comment by martin-242** [comment]
> Im using free tier Pinecone and it seems to work?

What is your environment name? Is your account new?
New accounts doesn't seem to work.

**Comment by timothycarambat** [comment]
Pinecone recently updated their model to where new subscribers/accounts do not have access to namespaces - we are working on supporting namespace-disabled Pinecone instances

**Comment by timothycarambat** [comment]
@ilanb @martin-242 Pinecone indexes that are in `gcp-starter` [which are limited](https://docs.pinecone.io/docs/starter-environment#limitations) are now fully feature complete with non-starter Pinecone instances.

- Sync Pinecone
- Reset DB
- Add documents via UI
- CRUD embeddings
- Migrate data to another provider or index
