### ISSUE TITLE
Open details document make blank page Docker

### ISSUE THREAD

**Issue by ilanb** [Mintplex-Labs/vector-admin#23]
Hi, tried to open cached documents after sync with Pinecone:
Document
857
Vectors
18.8 MiB
Vector Cache (MB)

When I click to open it, I see some ashes and after that quickly a blanc page (Chrome) 
No error appear in logs of Docker and no error in google chrome console

**Comment by timothycarambat** [comment]
Can you go to `http://localhost:3000/system-settings` and then using the database debug login to the VDBMS manager page.

After which navigate to the documentvectors table and ensure there are records present in there. No errors in console or otherwise?

**Comment by ilanb** [comment]
Documentation appear in the database correctly, just checked, no error in logs, please find log from docker
[Log.txt](https://github.com/Mintplex-Labs/vector-admin/files/12254347/Log.txt)

**Comment by timothycarambat** [comment]
How were these documents embedded? It appears that they are coming across with just the name `blob` which doesnt seem right as it should be a string and be the document's title

**Comment by ilanb** [comment]
I use OPENAI embeddings with Flowise, all documents are PDF files

**Comment by iokinpardo** [comment]
I confirm that using Flowise to upsert into Pinecone if you don't add specific metadata it does with "blob". I hope you find this helpful

**Comment by ilanb** [comment]
Thank you, If I understand I need to add metadata for each document in parameter ? title of document ?

**Comment by iokinpardo** [comment]
![image](https://github.com/Mintplex-Labs/vector-admin/assets/6673107/4cae2841-6b97-4501-b93a-fe92411338d8)
As you can see in the image the vectors created trough Flowise inot Pinecone without setting an specific title as metadata automatically are set with "blob". Just the one I upserted with "océano" seems to be showing fine within "Vector Admin".
Try upserting a simple TXT file and set a title and after check with "Vector Admin".

**Comment by ilanb** [comment]
Nice working fine !

**Comment by timothycarambat** [comment]
Wow @iokinpardo thats a nice detail to know 👀 

Closing this as it is exactly the same issue as #24. Missing `title` metadata. Going to move away from specific metadata field enforcement 👍
