### ISSUE TITLE
Connected Chroma, chroma/sync-workspace fails

### ISSUE THREAD

**Issue by arnoldligtvoet** [Mintplex-Labs/vector-admin#24]
Installed in Docker and connected to local docker Chroma instance. Can see my Workspaces. Clicked on Workspace and then 'Sync Workspace Data'. This queues a job that failes.

Job response:
{
  "canRetry": true,
  "message": "Job failed with error",
  "error": "Cannot read properties of null (reading 'title')",
  "details": {}
}

Chroma 0.4.4

**Comment by timothycarambat** [comment]
How was this data embedded? That seems to indicate that it cannot find a document title for the embedding in the metadata. Tools like Llama Index and Langchain _should_ attach the appropriate metadata

**Comment by arnoldligtvoet** [comment]
The data was embedded using Chroma with a local embedder. There is no metadata with the embedding, just document and ids.

**Comment by arnoldligtvoet** [comment]
Can confirm that rebuilding the collection with the metadatas: [{"title":"title"}] does work, although it does surprise me that this breaks the import of data, as it could use id instead of title if title is not present?

**Comment by timothycarambat** [comment]
> Can confirm that rebuilding the collection with the metadatas: [{"title":"title"}] does work, although it does surprise me that this breaks the import of data, as it could use id instead of title if title is not present?

Absolutely, will mark this as a bug because that's a very specific thing to expect. We will eventually not enforce any specific metadata at all and the table will be customizable to which columns you would want to display at all. Also add/update existing metadata fields as well

**Comment by timothycarambat** [comment]
moved to #40
