### ISSUE TITLE
How to install on Digital Ocean Droplet via Docker

### ISSUE THREAD

**Issue by pooriaarab** [Mintplex-Labs/vector-admin#36]
Went through the docs and found installation instructions for docker on windows but not docker on digital ocean droplet (linux - ubuntu). 

Got any tips on how to install it on digital ocean?

Found your tool from flowise discord. 

Also are you the people behind mintplex for Solana?

**Comment by pooriaarab** [comment]
LMFAO. Missed the blue link

https://github.com/Mintplex-Labs/vector-admin/blob/master/docker/DOCKER.md

**Comment by timothycarambat** [comment]
Did that docker file help you get this online on DO?

Also no, we never supported Solana for our [Launchpad](https://mintplex.xyz). Did you mean Metaplex?? Either that or someone stole our name 😆
