### ISSUE TITLE
Running yarn dev:setup returns ERROR: no such file or directory: dev:setup

### ISSUE THREAD

**Issue by pooriaarab** [Mintplex-Labs/vector-admin#37]
![image](https://github.com/Mintplex-Labs/vector-admin/assets/42897904/bd58662f-5a95-47e0-b2f1-93d07f45bbd9)

I see devSetup.js but can't run yarn dev:setup.js. 

Any idea why this is happening?

**Comment by timothycarambat** [comment]
You need to ensure `yarn` is installed on the system and available in the CLI. That is why it is saying `no such file or directory`.

Help: https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
