### ISSUE TITLE
yarn/docker issue

### ISSUE THREAD

**Issue by julianmorenomotta** [Mintplex-Labs/vector-admin#38]
The following error is yielded when runing `yarn dev:setup`

I'm using a macO S12.3.1

`the neares pacakage directory (../vector-admin/frontend) doesn't seem to be part of the project declared in (../vector-admin)`

and when trying to run 'docker-compose' comand, it naturaly yields

`failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::g7wxfdpmli2jkowdsir0lph1k: "/frontend/yarn.lock": not found`

**Comment by julianmorenomotta** [comment]
Also for some reason the discord link is not working for me

**Comment by hududed** [comment]
not sure if related, but here:

```
❯ yarn dev:setup
yarn run v1.22.10
warning ../../package.json: No license field
error vector-data-management-system@0.0.1-beta: The engine "node" is incompatible with this module. Expected version ">=18". Got "12.22.4"
error Commands cannot run with an incompatible environment.
```
Running mac OS 11.7.8

**Comment by timothycarambat** [comment]
@julianmorenomotta The discord link in the Readme?

Also what node version are you on? You can also just remove the yarn lockfile and then `cd frontend && yarn install`

**Comment by timothycarambat** [comment]
> not sure if related, but here:
> 
> ```
> ❯ yarn dev:setup
> yarn run v1.22.10
> warning ../../package.json: No license field
> error vector-data-management-system@0.0.1-beta: The engine "node" is incompatible with this module. Expected version ">=18". Got "12.22.4"
> error Commands cannot run with an incompatible environment.
> ```
> 
> Running mac OS 11.7.8

Not related, but you should be on Node `18+` as specified in the `.nvmrc` I believe the package.json at root is pegged only to 18.0.0. I am using 18.13.1

**Comment by BjoernRave** [comment]
do you maybe have a newer version than yarn v1 installed?

**Comment by julianmorenomotta** [comment]
> @julianmorenomotta The discord link in the Readme?
> 
> Also what node version are you on? You can also just remove the yarn lockfile and then `cd frontend && yarn install`

Yeah, but can figure out why. Now it worked.
