### ISSUE TITLE
Document Metadata field editor.

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/vector-admin#40]
On each document, we should allow the editing of metadata and optionally enable the editing of chunk metadata. 

So at the document level, we can apply or remove key/value pairs and on the chunk level be allowed to do the same.

This will not cover multi-selection. It is either the entire document or a single chunk.

**Comment by umair313** [comment]
+1
I think currently dashboard is not showing metadata at all.

**Comment by timothycarambat** [comment]
Correct, this will be where it can be shown and edited
