### ISSUE TITLE
Can't connect to Chroma

### ISSUE THREAD

**Issue by devaniljr** [Mintplex-Labs/vector-admin#51]
I have a Chroma instance in the AWS, it's currently open without authorization. But every time I try to connect using the IP address, it says "Could not connect to Chroma instance with those credentials.", even if the API Header & Key its empty.

**Comment by timothycarambat** [comment]
Did you deploy the AWS API and are you able to go to `<API_GATEWAY_URL>/api/v1` and get a heartbeat response?

**Comment by devaniljr** [comment]
Yes, I get a

```
{
"nanosecond heartbeat": 1695146874540770000
}
```

**Comment by timothycarambat** [comment]
Are you inputting just the `API_GATEWAY` part of the URL? Basically everything before `/api` should be there, including https
