### ISSUE TITLE
uploading a PDF file only 1 vector 

### ISSUE THREAD

**Issue by Nikto655** [Mintplex-Labs/vector-admin#57]
I tried to upload a pdf file that consists of 20+ pages, but it seems that only the title page was uploaded. There only 1 vector present after uploading.

**Comment by timothycarambat** [comment]
You should inspect the resulting `documents` object that is created. It is possible that your PDF is not parseable from its source. This could be for many reasons (encoding, language, special text, PDF text is encoded as image)
