### ISSUE TITLE
Documet view with no content to display from the text crashes page

### ISSUE THREAD

**Issue by carrigan223** [Mintplex-Labs/vector-admin#65]
When viewing a document after upload if it was uploaded with no text crashes the page. I uploaded a document without a text field in the metadata, in the next frontend component of the table view when looking at the document the page flashes and crashes. the console error is that .length is trying to be called against null. My suspicion is that the content preview pill is checking length regardless of whether the property is present when trying to display the row component in the document view.

**Comment by timothycarambat** [comment]
Related to the migration of the WASM import improvement to the lighter-weight Text encoder. Resolved by 5f0e392afb80b47e904371cc025ca21a9b9cba84
