### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by netandreus** [Mintplex-Labs/vector-admin#76]
Do you plan support sqlite instead of postgresql?
I think it will be comfortable for small instalaltions.

**Comment by timothycarambat** [comment]
We actually used to use SQLite! But we had a ton of concurrency issues and massive performance problems when dealing with really large vector databases + background jobs. It was causing a bunch of issues so we moved away from it.

Limitations for SQLite + Primsa like deleteMany not being available was also very frustrating so we had to move to something less lightweight, but more robust. 

I like SQLite! We use it for [AnythingLLM](https://github.com/Mintplex-Labs/anything-llm)!
