### ISSUE TITLE
Cant access the UI from a remote box

### ISSUE THREAD

**Issue by shyamsfo** [Mintplex-Labs/vector-admin#9]
Nice work. Comes up fine...

I am running using `docker-compose up -d --build`

What's the way to access the UI from a remote box? 
Something in the frontend always tries to authenticate to `127.0.0.1:3001/api/`

I see a `VITE_API_BASE` variable but I am not sure where to set this (and what to rebuild (for docker) after setting it)

**Comment by timothycarambat** [comment]
User interface URL is `127.0.0.1:3001` or `localhost:3001`!

**Comment by shyamsfo** [comment]
yes, that works and the login page comes up, but the moment i type my username and password, it tries to authenticate at 127.0.0.1:3001 not the remote ip.
![Screenshot 2023-07-28 at 8 48 47 PM](https://github.com/Mintplex-Labs/vector-admin/assets/13055215/91c38d81-6a56-4075-af31-153069276352)

**Comment by wiaa1234** [comment]
@timothycarambat I am having the Same Issue, auth requests are being sent to my Local Docker Engine instead of the Repo I have on Google Cloud Run. The app wont Authenticate anyone without Docker Running Local on my machine. What Should I do? Thanks.

**Comment by timothycarambat** [comment]
So to clarify, are you running docker on an EC2-like instance that is available via some IP address?

**Comment by shyamsfo** [comment]
Yes.  Patch below doesnt completely fix it, but this should be the starting point of your fix.
[remote.patch](https://github.com/Mintplex-Labs/vector-admin/files/12231355/remote.patch)
