### ISSUE TITLE
Organization "tech@MyDomain.ai" causes 404

### ISSUE THREAD

**Issue by sglebs** [Mintplex-Labs/vector-admin#91]
I am adding multiple organizations as a means to connect to multiple different vector db technologies.

On my 2nd Org I defined the name to be: tech@MyDomain.ai

After it is created and the left menu is populated, if you click on it you will get a 404"

```
This localhost page can’t be foundNo webpage was found for the web address: http://localhost:3000/dashboard/tech@MyDomain.ai
HTTP ERROR 404
```

BTW, how can I delete the Org?

**Comment by timothycarambat** [comment]
Ah, it would be the inclusion of special characters "@" and "." being at the end of the path in this case. To delete the organization you can directly navigate to http://localhost:3000/dashboard/tech@MyDomain.ai/settings and you should be able to delete on that screen.

Will make an issue for this!

**Comment by sglebs** [comment]
> Ah, it would be the inclusion of special characters "@" and "." being at the end of the path in this case. To delete the organization you can directly navigate to http://localhost:3000/dashboard/tech@MyDomain.ai/settings and you should be able to delete on that screen.
> 
> Will make an issue for this!

When I visit this crafted link it takes me to a valid Org which I do not want to delete. I am still unable to delete the org with @ and . in its name.

**Comment by timothycarambat** [comment]
You should then do this directly in the database itself, you can get the login credentials by going to any organizations settings and going to the bottom of the page where you can find "Debug Credentials" and you can login to the database debugger and delete the organization directly.
