### ISSUE TITLE
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum : "/document-processor": not found

### ISSUE THREAD

**Issue by JairajGaur** [Mintplex-Labs/vector-admin#99]
Hi,
   I'm trying to do docker build using the below command. However, this is generating the error during coping document-processor folder everytime. Could you please check and confirm if this is known issue and what's the resolution. I tried multiple solution but nothing worked for me.

Command : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker build --pull --rm -f "docker\Dockerfile" -t vectoradmin:latest "docker"

-----------------------------------------------------
Error : --------------------
  75 |
  76 |     # Copy the document-processor
  77 | >>> COPY ./document-processor/ ./document-processor/
  78 |
  79 |     # Install document-processor dependencies
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 5627e5d8-6272-4427-9297-c31a310b5758::5oax43ihn5e9096cd6sgw8e1w: "/document-processor": not found
-----------------------------------------------------
Branch - master

**Comment by timothycarambat** [comment]
Can you try running docker build from within the `docker/` folder instead of outside of it? The Docker context is not root of the repo and is instead from within the docker folder.

**Comment by JairajGaur** [comment]
It's working if I run below commands within the docker/. 
docker-compose up -d --build postgres 
docker-compose up -d --build vector-admin

But issue wasn't an issue few days back as I was able to build using Dockerfile directly. This started happening since yesterday.

**Comment by timothycarambat** [comment]
I just did a rebuild using `docker-compose up -d --build vector-admin` and did not crash. Im not sure how the document-processor folder is missing on your build, since that is typically the case of a `COPY` not working. The folder is there for sure?

**Comment by timothycarambat** [comment]
To add onto this, we also have automated docker builds that are pushed to [Docker Hub](https://hub.docker.com/r/mintplexlabs/vectoradmin) which are also not failing

**Comment by JairajGaur** [comment]
> I just did a rebuild using `docker-compose up -d --build vector-admin` and did not crash. Im not sure how the document-processor folder is missing on your build, since that is typically the case of a `COPY` not working. The folder is there for sure?

Yes, the folder is there for sure. The other way of running the docker for vector-admin and Postgres are working fine. Just one more extra point to add regarding my local setup. I'm using windows OS for my setup.

**Comment by rawpixel-vincent** [comment]
I had the same issue to build the image from the Dockerfile
you need to run with the context at the root of the repo

From the root of the repository:
```
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker build . --pull --rm -f "docker\Dockerfile" -t vectoradmin:latest "docker"
```

was running on linux so not entirely sure about the powershell syntax above

what worked for me
```
docker build . -f ./docker/Dockerfile
```

**Comment by timothycarambat** [comment]
Correct, referring to the docker-compose you can see the context is `../` when inside of the `docker` folder. So if not using the docker-compose in the repo you need to target the DockerFile from the root directory. Apologies for the confusion but then the paths during copying will be correct in the DockerFile.
